services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mini-order-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "11433:1433"